services:
  db:
    hostname: db
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  pubsub:
    image: messagebird/gcloud-pubsub-emulator:latest
    ports:
      - "8681:8681"
    environment:
      PUBSUB_PROJECT1: "local-project,poo-pad-pong-topic:poo-pad-pong-subscription"  # projectId,Topic:Subscription
