[package]
name = "domain"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
regex = "1.8.1"
thiserror = "1.0.40"
