//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::fields::Entity as Fields;
pub use super::keys::Entity as Keys;
pub use super::objects::Entity as Objects;
pub use super::rules::Entity as Rules;
