//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "generation_type")]
pub enum GenerationType {
    #[sea_orm(string_value = "Equals")]
    Equals,
    #[sea_orm(string_value = "Regex")]
    Regex,
}
